package com.stanleymesa.core.utlis

// PREF
const val USER_PREF = "user_pref"

// API STATUS
const val LOGIN_SUCCESS = "LOGIN SUCCESS"
const val LOGIN_FAILED = "LOGIN FAILED"
const val REGISTER_SUCCESS = "REGISTER SUCCESSFUL"
const val DELETE_SUCCESS = "DELETE SUCCESS"
const val STATUS_OK = "OK"
const val STATUS_UNAUTHORIZED = 401

// INTENT
const val REFRESH_PRODUCT = 100
const val REFRESH_SUPPLIER = 101
const val GET_SUPPLIER = 102
const val REFRESH_UPDATED_PRODUCT = 103
const val REFRESH_UPDATED_SUPPLIER = 106
const val REFRESH_NOTFOUND_PRODUCT = 104
const val REFRESH_NOTFOUND_SUPPLIER = 105
const val INTENT_SUPPLIER = "INTENT_SUPPLIER"
const val INTENT_PRODUCT_ID = "INTENT_PRODUCT_ID"
const val INTENT_SUPPLIER_ID = "INTENT_SUPPLIER_ID"
const val SNACKBAR_VALUE = "SNACKBAR_VALUE"